name: ssdlc-sbom
on:
  workflow_call:
    inputs:
      sbom_name:
        description: "Name for the SBOM file"
        required: true
        type: string

      ref:
        description: Branch, tag, or commit to scan
        required: false
        type: string
        default: ""

      include_submodules:
        description: Whether to checkout submodules recursively
        required: false
        type: boolean
        default: true

jobs:
  syft-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          submodules: ${{ inputs.include_submodules && 'recursive' || 'false' }}
          persist-credentials: false

      - name: Generate CycloneDX SBOM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          format: cyclonedx-json
          artifact-name: ${{ inputs.sbom_name }}.cyclonedx.json
          upload-release-assets: true
          dependency-snapshot: true
